#
# Copyright 2023 DimOnOff inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += rve_gateway.o

ifdef CONFIG_SPL_BUILD
obj-y += ../../variscite/imx8mn_var_som/spl.o
obj-y += ../../variscite/imx8mn_var_som/ddr4_timing.o
endif
